project_id = "sdeafsjyaaijtowpsjbu"

[functions.shoplanser-proxy]
verify_jwt = false

[functions.store-og]
verify_jwt = false

[functions.support-request]
verify_jwt = false

[functions.mcp]
verify_jwt = false
