/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalRefundRouteImport } from './routes/legal/refund'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as MarketplaceCategoryRouteImport } from './routes/marketplace/$category'
import { Route as StoreSlugRouteImport } from './routes/store/$slug'
import { Route as VendorApplyRouteImport } from './routes/vendor/apply'
import { Route as VendorDashboardRouteImport } from './routes/vendor/dashboard'
import { Route as VendorLoginRouteImport } from './routes/vendor/login'
import { Route as VendorSuccessRouteImport } from './routes/vendor/success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceCategoryRoute = MarketplaceCategoryRouteImport.update({
  id: '/marketplace/$category',
  path: '/marketplace/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorApplyRoute = VendorApplyRouteImport.update({
  id: '/vendor/apply',
  path: '/vendor/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorLoginRoute = VendorLoginRouteImport.update({
  id: '/vendor/login',
  path: '/vendor/login',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSuccessRoute = VendorSuccessRouteImport.update({
  id: '/vendor/success',
  path: '/vendor/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/marketplace/$category': typeof MarketplaceCategoryRoute
  '/store/$slug': typeof StoreSlugRoute
  '/vendor/apply': typeof VendorApplyRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/login': typeof VendorLoginRoute
  '/vendor/success': typeof VendorSuccessRoute
  '/blog/': typeof BlogIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/marketplace/$category': typeof MarketplaceCategoryRoute
  '/store/$slug': typeof StoreSlugRoute
  '/vendor/apply': typeof VendorApplyRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/login': typeof VendorLoginRoute
  '/vendor/success': typeof VendorSuccessRoute
  '/blog': typeof BlogIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/marketplace/$category': typeof MarketplaceCategoryRoute
  '/store/$slug': typeof StoreSlugRoute
  '/vendor/apply': typeof VendorApplyRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/login': typeof VendorLoginRoute
  '/vendor/success': typeof VendorSuccessRoute
  '/blog/': typeof BlogIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/marketplace/$category'
    | '/store/$slug'
    | '/vendor/apply'
    | '/vendor/dashboard'
    | '/vendor/login'
    | '/vendor/success'
    | '/blog/'
    | '/marketplace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/marketplace/$category'
    | '/store/$slug'
    | '/vendor/apply'
    | '/vendor/dashboard'
    | '/vendor/login'
    | '/vendor/success'
    | '/blog'
    | '/marketplace'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/marketplace/$category'
    | '/store/$slug'
    | '/vendor/apply'
    | '/vendor/dashboard'
    | '/vendor/login'
    | '/vendor/success'
    | '/blog/'
    | '/marketplace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalTermsRoute: typeof LegalTermsRoute
  MarketplaceCategoryRoute: typeof MarketplaceCategoryRoute
  StoreSlugRoute: typeof StoreSlugRoute
  VendorApplyRoute: typeof VendorApplyRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorLoginRoute: typeof VendorLoginRoute
  VendorSuccessRoute: typeof VendorSuccessRoute
  BlogIndexRoute: typeof BlogIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$category': {
      id: '/marketplace/$category'
      path: '/marketplace/$category'
      fullPath: '/marketplace/$category'
      preLoaderRoute: typeof MarketplaceCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/apply': {
      id: '/vendor/apply'
      path: '/vendor/apply'
      fullPath: '/vendor/apply'
      preLoaderRoute: typeof VendorApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/login': {
      id: '/vendor/login'
      path: '/vendor/login'
      fullPath: '/vendor/login'
      preLoaderRoute: typeof VendorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/success': {
      id: '/vendor/success'
      path: '/vendor/success'
      fullPath: '/vendor/success'
      preLoaderRoute: typeof VendorSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalTermsRoute: LegalTermsRoute,
  MarketplaceCategoryRoute: MarketplaceCategoryRoute,
  StoreSlugRoute: StoreSlugRoute,
  VendorApplyRoute: VendorApplyRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorLoginRoute: VendorLoginRoute,
  VendorSuccessRoute: VendorSuccessRoute,
  BlogIndexRoute: BlogIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
