// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-zones.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
var list_zones_default = defineTool({
  name: "list_zones",
  title: "List delivery zones",
  description: "List the Shoplanser delivery zones available for stores.",
  inputSchema: {},
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async () => {
    const res = await fetch(
      "https://dashboard.shoplanser.com/api/v1/zone/list",
      {
        headers: { "X-localization": "en", Accept: "application/json" }
      }
    );
    const text = await res.text();
    if (!res.ok) {
      return {
        content: [
          {
            type: "text",
            text: `Failed (${res.status}): ${text.slice(0, 300)}`
          }
        ],
        isError: true
      };
    }
    return { content: [{ type: "text", text }] };
  }
});

// src/lib/mcp/tools/list-modules.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.24.2";
var list_modules_default = defineTool2({
  name: "list_modules",
  title: "List store modules",
  description: "List the Shoplanser store modules (business types), optionally filtered by zone.",
  inputSchema: {
    zone_id: z.number().int().positive().optional().describe("Optional zone id to filter modules.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async ({ zone_id }) => {
    const path = zone_id ? `/module?zone_id=${zone_id}` : "/module";
    const headers = {
      "X-localization": "en",
      Accept: "application/json"
    };
    if (zone_id) headers.zoneId = `[${zone_id}]`;
    const res = await fetch(`https://dashboard.shoplanser.com/api/v1${path}`, {
      headers
    });
    const text = await res.text();
    if (!res.ok) {
      return {
        content: [
          {
            type: "text",
            text: `Failed (${res.status}): ${text.slice(0, 300)}`
          }
        ],
        isError: true
      };
    }
    return { content: [{ type: "text", text }] };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.24.2";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List Shoplanser categories, optionally scoped to a store module.",
  inputSchema: {
    module_id: z2.number().int().positive().optional().describe("Optional module id to filter categories.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async ({ module_id }) => {
    const headers = {
      "X-localization": "en",
      Accept: "application/json"
    };
    if (module_id) headers.moduleId = String(module_id);
    const res = await fetch(
      `https://dashboard.shoplanser.com/api/v1/categories`,
      { headers }
    );
    const text = await res.text();
    if (!res.ok) {
      return {
        content: [
          {
            type: "text",
            text: `Failed (${res.status}): ${text.slice(0, 300)}`
          }
        ],
        isError: true
      };
    }
    return { content: [{ type: "text", text }] };
  }
});

// src/lib/mcp/tools/list-stores.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.24.2";
var list_stores_default = defineTool4({
  name: "list_stores",
  title: "List stores by module",
  description: "List Shoplanser stores for a given module (business type), with optional zone and pagination.",
  inputSchema: {
    module_id: z3.number().int().positive().describe("The store module id."),
    zone_id: z3.number().int().positive().default(1).describe("Zone id (defaults to 1)."),
    limit: z3.number().int().min(1).max(100).default(20).describe("Max stores to return."),
    offset: z3.number().int().min(1).default(1).describe("Page offset (1-based).")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async ({ module_id, zone_id, limit, offset }) => {
    const res = await fetch(
      `https://dashboard.shoplanser.com/api/v1/stores/get-stores/all?offset=${offset}&limit=${limit}`,
      {
        headers: {
          "X-localization": "en",
          Accept: "application/json",
          moduleId: String(module_id),
          zoneId: `[${zone_id}]`,
          latitude: "30.033333",
          longitude: "31.233334"
        }
      }
    );
    const text = await res.text();
    if (!res.ok) {
      return {
        content: [
          {
            type: "text",
            text: `Failed (${res.status}): ${text.slice(0, 300)}`
          }
        ],
        isError: true
      };
    }
    return { content: [{ type: "text", text }] };
  }
});

// src/lib/mcp/tools/check-slug.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.24.2";
var check_slug_default = defineTool5({
  name: "check_store_slug",
  title: "Check store slug availability",
  description: "Check whether a store slug is already taken on Shoplanser.",
  inputSchema: {
    slug: z4.string().trim().min(1).describe("The store slug to check.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: true
  },
  handler: async ({ slug }) => {
    const res = await fetch(
      `https://dashboard.shoplanser.com/api/v1/store/check-slug/${encodeURIComponent(slug)}`,
      { headers: { "X-localization": "en", Accept: "application/json" } }
    );
    const text = await res.text();
    if (!res.ok) {
      return {
        content: [
          {
            type: "text",
            text: `Failed (${res.status}): ${text.slice(0, 300)}`
          }
        ],
        isError: true
      };
    }
    return { content: [{ type: "text", text }] };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "shoplanser-mcp",
  title: "Shoplanser MCP",
  version: "0.1.0",
  instructions: "Public read-only tools for the Shoplanser marketplace: browse delivery zones, store modules (business types), categories, and stores, and check if a store slug is available before registering a new store.",
  tools: [list_zones_default, list_modules_default, list_categories_default, list_stores_default, check_slug_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
